image: mcr.microsoft.com/dotnet/sdk:latest

stages:
  - build

build_job:
  stage: build
  tags: [docker-executor]
  script:
    - 'cd Backend/TriviaSolution'
    - 'dotnet restore'
    - 'dotnet build --no-restore'
