version: "3.9"
services:
  db:
    image: 'postgres:15.8-alpine3.20'
    ports:
      - "5432:5432"
    container_name: db
    volumes:
      - smartspin-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  smartspin-db: