version: "3.9"
services:
  db:
    image: 'postgres:15.8-alpine3.20'
    ports:
      - "5432:5432"
    container_name: db
    volumes:
      - smartspin-db:/var/lib/postgresql/data
    env_file: .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    container_name: api
    image: 'afilipovski/smart-spin:latest'
    ports:
      - "8080:8080"
    build:
      context: .
    volumes:
      - ./serviceAccountKey.json:/app/serviceAccountKey.json
    env_file: .env
    depends_on:
      db:
        condition: service_healthy

volumes:
  smartspin-db: