// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmCTp_cTWtpOFRIW-v9N0safUM_qIpCXI',
    appId: '1:308117439977:android:02e8733af41fa32073f778',
    messagingSenderId: '308117439977',
    projectId: 'smart-spin-83f3e',
    androidClientId: 
      '308117439977-380rqfv11tbniib2knsod2fhdgpu7gnm.apps.googleusercontent.com',
    iosClientId: 
      '308117439977-hredna3g3v07vmarbddbjt9qqae7auv5.apps.googleusercontent.com',
    databaseURL: 'https://smart-spin-83f3e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smart-spin-83f3e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUiVrA-gi7R4YNKmrl2wZlRIMdCSjIjv4',
    appId: '1:308117439977:ios:a2e2c9c5964e7b7c73f778',
    messagingSenderId: '308117439977',
    projectId: 'smart-spin-83f3e',
    databaseURL: 'https://smart-spin-83f3e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smart-spin-83f3e.firebasestorage.app',
    androidClientId:
        '308117439977-380rqfv11tbniib2knsod2fhdgpu7gnm.apps.googleusercontent.com',
    iosClientId:
        '308117439977-hredna3g3v07vmarbddbjt9qqae7auv5.apps.googleusercontent.com',
    iosBundleId: 'com.smart.spin',
  );
}
