// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmCTp_cTWtpOFRIW-v9N0safUM_qIpCXI',
    appId: '1:308117439977:android:149b23bc5ef745ad73f778',
    messagingSenderId: '308117439977',
    projectId: 'smart-spin-83f3e',
    databaseURL: 'https://smart-spin-83f3e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smart-spin-83f3e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUiVrA-gi7R4YNKmrl2wZlRIMdCSjIjv4',
    appId: '1:308117439977:ios:bac075149d77f0f773f778',
    messagingSenderId: '308117439977',
    projectId: 'smart-spin-83f3e',
    databaseURL: 'https://smart-spin-83f3e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smart-spin-83f3e.firebasestorage.app',
    androidClientId: '308117439977-380rqfv11tbniib2knsod2fhdgpu7gnm.apps.googleusercontent.com',
    iosClientId: '308117439977-tqbk62ih53p1uubfoj1a3er472mg2gsu.apps.googleusercontent.com',
    iosBundleId: 'com.example.triviaApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7RDRd_9pWF6XZ6DZ5lNIbnKYi360eyvI',
    appId: '1:308117439977:web:63ba2a59c8aa78b573f778',
    messagingSenderId: '308117439977',
    projectId: 'smart-spin-83f3e',
    authDomain: 'smart-spin-83f3e.firebaseapp.com',
    databaseURL: 'https://smart-spin-83f3e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smart-spin-83f3e.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUiVrA-gi7R4YNKmrl2wZlRIMdCSjIjv4',
    appId: '1:308117439977:ios:bac075149d77f0f773f778',
    messagingSenderId: '308117439977',
    projectId: 'smart-spin-83f3e',
    databaseURL: 'https://smart-spin-83f3e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smart-spin-83f3e.firebasestorage.app',
    androidClientId: '308117439977-380rqfv11tbniib2knsod2fhdgpu7gnm.apps.googleusercontent.com',
    iosClientId: '308117439977-tqbk62ih53p1uubfoj1a3er472mg2gsu.apps.googleusercontent.com',
    iosBundleId: 'com.example.triviaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7RDRd_9pWF6XZ6DZ5lNIbnKYi360eyvI',
    appId: '1:308117439977:web:d9c40e5c133f314173f778',
    messagingSenderId: '308117439977',
    projectId: 'smart-spin-83f3e',
    authDomain: 'smart-spin-83f3e.firebaseapp.com',
    databaseURL: 'https://smart-spin-83f3e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smart-spin-83f3e.firebasestorage.app',
  );

}